
# PostgreSQL DataSource
spring.datasource.url= jdbc:postgresql://localhost:5432/postgres
spring.datasource.username= postgres
spring.datasource.password= postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=dGhpcy1pcy1hLXZlcnktc2VjdXJlLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbnMtMjAyNg==
app.jwt.expiration-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dvdungg06@gmail.com
spring.mail.password=zgnc zerl zlss pmch
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name= dydummtx2
cloudinary.api-key=321161744879916
cloudinary.api-secret=5qYTrTqNOo_kM1U-TGpsgkOwhn8
cloudinary.upload-folder=guangzhou-chat
cloudinary.max-file-size-mb=5

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



# PayOS Payment Gateway
payos.client-id=5ec0a0bd-2fc6-4355-817a-c332caf2fd6b
payos.api-key=d29d8c96-b286-47cc-8e91-858bdd65c39f
payos.checksum-key=9704e000f61994c9f9b1e7733314066d228d753a4b73493d50c986786180233c

app.frontend.base-url=http://localhost:8080
